config/routes.rb
Rails.application.routes.draw do
  get 'catalog' => 'catalog#index'

  get 'catalog/:category' => 'catalog#category'

  get 'catalog/:category/:item' => 'catalog#item'

  get 'cart'  => 'cart#index'

  get 'cart/checkout' => 'cart#checkout'

  post 'cart/order' => 'cart#order'

  get 'cart/success' => 'cart#success'

    get 'userlist/' => 'userlist#index'

    get 'userlist/show'

  namespace :admin do
    resources :orders
  end
  namespace :admin do
    resources :paytypes
  end
  namespace :admin do
    resources :pages
  end
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  namespace :admin do
    resources :reviews
  end
  namespace :admin do
    resources :postcomments
  end
  namespace :admin do
    resources :tags
  end
  namespace :admin do
    resources :posts
  end
  namespace :admin do
    resources :comments
  end
  namespace :admin do
    resources :actions
  end
  namespace :admin do
    resources :items
  end
  namespace :admin do
    resources :categories
  end

  root 'index#index'

  post '/addtocart' => 'cart#add' 

end

app/views/admin/pages/_form.html.erb
<%= form_for(@admin_page) do |f| %>
  <% if @admin_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_page.errors.count, "error") %> prohibited this admin_page from being saved:</h2>

      <ul>
      <% @admin_page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content, class: "form-control ckeditor" %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit "Сохранить", :class => "btn btn-default" %>
  </div>
<% end %>

app/views/admin/pages/edit.html.erb
<h1>Редактировать страницу</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_page %> |
<%= link_to 'Back', admin_pages_path %>

app/views/admin/pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Список страниц</h1>

<table class="table table-responsive">
  <thead>
    <tr>
      <th>Название</th>
      <th>Контент</th>
      <th>Картинка</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_pages.each do |admin_page| %>
      <tr>
        <td><%= admin_page.title %></td>
        <td><%= admin_page.content %></td>
        <td><%= admin_page.image %></td>
        <td><%= link_to 'Show', admin_page %></td>
        <td><%= link_to 'Edit', edit_admin_page_path(admin_page) %></td>
        <td><%= link_to 'Destroy', admin_page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_admin_page_path %>

app/views/admin/pages/new.html.erb
<h1>Создать новую страницу</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_pages_path %>

app/views/admin/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @admin_page.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @admin_page.content %>
</p>

<p>
  <strong>Image:</strong>
  <%= @admin_page.image %>
</p>

<%= link_to 'Edit', edit_admin_page_path(@admin_page) %> |
<%= link_to 'Back', admin_pages_path %>