config/routes.rb
Rails.application.routes.draw do
  get 'catalog' => 'catalog#index'

  get 'catalog/:category' => 'catalog#category'

  get 'catalog/:category/:item' => 'catalog#item'

  get 'cart'  => 'cart#index'

  get 'cart/checkout' => 'cart#checkout'

  post 'cart/order' => 'cart#order'

  get 'cart/success' => 'cart#success'

    get 'userlist/' => 'userlist#index'

    get 'userlist/show'

  namespace :admin do
    resources :orders
  end
  namespace :admin do
    resources :paytypes
  end
  namespace :admin do
    resources :pages
  end
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  namespace :admin do
    resources :reviews
  end
  namespace :admin do
    resources :postcomments
  end
  namespace :admin do
    resources :tags
  end
  namespace :admin do
    resources :posts
  end
  namespace :admin do
    resources :comments
  end
  namespace :admin do
    resources :actions
  end
  namespace :admin do
    resources :items
  end
  namespace :admin do
    resources :categories
  end

  root 'index#index'

  post '/addtocart' => 'cart#add' 

end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
  layout "admin"
  before_filter :custom_user_auth
  before_action :set_admin_review, only: [:show, :edit, :update, :destroy]

  # GET /admin/reviews
  # GET /admin/reviews.json
  def index
    @admin_reviews = Admin::Review.all
  end

  # GET /admin/reviews/1
  # GET /admin/reviews/1.json
  def show
  end

  # GET /admin/reviews/new
  def new
    @admin_review = Admin::Review.new
  end

  # GET /admin/reviews/1/edit
  def edit
  end

  # POST /admin/reviews
  # POST /admin/reviews.json
  def create
    @admin_review = Admin::Review.new(admin_review_params)

    respond_to do |format|
      if @admin_review.save
        format.html { redirect_to @admin_review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @admin_review }
      else
        format.html { render :new }
        format.json { render json: @admin_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/reviews/1
  # PATCH/PUT /admin/reviews/1.json
  def update
    respond_to do |format|
      if @admin_review.update(admin_review_params)
        format.html { redirect_to @admin_review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_review }
      else
        format.html { render :edit }
        format.json { render json: @admin_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/reviews/1
  # DELETE /admin/reviews/1.json
  def destroy
    @admin_review.destroy
    respond_to do |format|
      format.html { redirect_to admin_reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_review
      @admin_review = Admin::Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_review_params
      params.require(:admin_review).permit(:name, :city, :text, :foto)
    end
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/views/admin/reviews/_form.html.erb
<%= form_for(@admin_review) do |f| %>
  <% if @admin_review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_review.errors.count, "error") %> prohibited this admin_review from being saved:</h2>

      <ul>
      <% @admin_review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text, class: "form-control ckeditor" %>
  </div>
  <div class="field">
    <%= f.label :foto %><br>
    <%= f.file_field :foto %>
  </div>
  <div class="actions">
    <%= f.submit "Сохранить", :class => "btn btn-default" %>
  </div>
<% end %>

app/views/admin/reviews/edit.html.erb
<h1>Editing Admin Review</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_review %> |
<%= link_to 'Back', admin_reviews_path %>

app/views/admin/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Отзывы клиентов</h1>

<table class="table table-responsive">
  <thead>
    <tr>
      <th>Имя</th>
      <th>Город</th>
      <th>Отзыв</th>
      <th>Фото</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_reviews.each do |admin_review| %>
      <tr>
        <td><%= admin_review.name %></td>
        <td><%= admin_review.city %></td>
        <td><%= admin_review.text %></td>
        <td><%= image_tag admin_review.foto, :size => "100x100" %></td>
        <td><%= link_to 'Show', admin_review %></td>
        <td><%= link_to 'Edit', edit_admin_review_path(admin_review) %></td>
        <td><%= link_to 'Destroy', admin_review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_admin_review_path %>

app/views/admin/reviews/new.html.erb
<h1>New Admin Review</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_reviews_path %>

app/views/admin/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin_review.name %>
</p>

<p>
  <strong>City:</strong>
  <%= @admin_review.city %>
</p>

<p>
  <strong>Text:</strong>
  <%= @admin_review.text %>
</p>

<p>
  <strong>Foto:</strong>
  <%= @admin_review.foto %>
</p>

<%= link_to 'Edit', edit_admin_review_path(@admin_review) %> |
<%= link_to 'Back', admin_reviews_path %>