config/routes.rb
Rails.application.routes.draw do
  get 'catalog' => 'catalog#index'

  get 'catalog/:category' => 'catalog#category'

  get 'catalog/:category/:item' => 'catalog#item'

  get 'cart'  => 'cart#index'

  get 'cart/checkout' => 'cart#checkout'

  post 'cart/order' => 'cart#order'

  get 'cart/success' => 'cart#success'

    get 'userlist/' => 'userlist#index'

    get 'userlist/show'

  namespace :admin do
    resources :orders
  end
  namespace :admin do
    resources :paytypes
  end
  namespace :admin do
    resources :pages
  end
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  namespace :admin do
    resources :reviews
  end
  namespace :admin do
    resources :postcomments
  end
  namespace :admin do
    resources :tags
  end
  namespace :admin do
    resources :posts
  end
  namespace :admin do
    resources :comments
  end
  namespace :admin do
    resources :actions
  end
  namespace :admin do
    resources :items
  end
  namespace :admin do
    resources :categories
  end

  root 'index#index'

  post '/addtocart' => 'cart#add' 

end

app/models/admin/order.rb
class Admin::Order < ActiveRecord::Base
  belongs_to :paytype, :class_name => "Paytype"
  has_and_belongs_to_many :items
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  layout "admin"
  before_action :set_admin_order, only: [:show, :edit, :update, :destroy]

  # GET /admin/orders
  # GET /admin/orders.json
  def index
    @admin_orders = Admin::Order.all
  end

  # GET /admin/orders/1
  # GET /admin/orders/1.json
  def show
  end

  # GET /admin/orders/new
  def new
    @admin_order = Admin::Order.new
  end

  # GET /admin/orders/1/edit
  def edit
  end

  # POST /admin/orders
  # POST /admin/orders.json
  def create
    @admin_order = Admin::Order.new(admin_order_params)

    respond_to do |format|
      if @admin_order.save
        
        format.html { redirect_to @admin_order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @admin_order }
      else
        format.html { render :new }
        format.json { render json: @admin_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/orders/1
  # PATCH/PUT /admin/orders/1.json
  def update
    respond_to do |format|
      if @admin_order.update(admin_order_params)

        format.html { redirect_to @admin_order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_order }
      else
        format.html { render :edit }
        format.json { render json: @admin_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/orders/1
  # DELETE /admin/orders/1.json
  def destroy
    @admin_order.destroy
    respond_to do |format|
      format.html { redirect_to admin_orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_order
      @admin_order = Admin::Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_order_params
      params.require(:admin_order).permit(:name, :email, :summ, :payed, :paytype_id, :phone, :comment, :item_ids)
    end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/_form.html.erb
<%= form_for(@admin_order) do |f| %>
  <% if @admin_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_order.errors.count, "error") %> prohibited this admin_order from being saved:</h2>

      <ul>
      <% @admin_order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :summ %><br>
    <%= f.number_field :summ, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :payed %><br>
    <%= f.check_box :payed %>
  </div>
  <div class="field">
    <%= f.label :paytype_id %><br>
    <%= f.collection_select(:paytype_id, Admin::Paytype.all, :id, :title) %>
  </div>
  <div class="field">
    <%= f.label :item_ids %><br>
    <%= f.collection_select(:item_ids, Admin::Item.all, :id, :title) %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment, class: "form-control ckeditor" %>
  </div>
  <div class="actions">
    <%= f.submit "Сохранить", :class => "btn btn-default" %>
  </div>
<% end %>

app/views/admin/orders/edit.html.erb
<h1>Editing Admin Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_order %> |
<%= link_to 'Back', admin_orders_path %>

app/views/admin/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Заказы</h1>

<table class="table table-responsive">
  <thead>
    <tr>
      <th>Имя</th>
      <th>Email</th>
      <th>Сумма</th>
      <th>Оплачено</th>
      <th>Способ оплаты</th>
      <th>Телефон</th>
      <th>Комментарий</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_orders.each do |admin_order| %>
      <tr>
        <td><%= admin_order.name %></td>
        <td><%= admin_order.email %></td>
        <td><%= admin_order.summ %></td>
        <td><%= admin_order.payed %></td>
        <td><%= admin_order.paytype.title %></td>
        <td><%= admin_order.phone %></td>
        <td><%= admin_order.comment %></td>
        <td><%= link_to 'Show', admin_order %></td>
        <td><%= link_to 'Edit', edit_admin_order_path(admin_order) %></td>
        <td><%= link_to 'Destroy', admin_order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_admin_order_path %>

app/views/admin/orders/new.html.erb
<h1>New Admin Order</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_orders_path %>

app/views/admin/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin_order.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @admin_order.email %>
</p>

<p>
  <strong>Summ:</strong>
  <%= @admin_order.summ %>
</p>

<p>
  <strong>Payed:</strong>
  <%= @admin_order.payed %>
</p>

<p>
  <strong>Paytype:</strong>
  <%= @admin_order.paytype.title %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @admin_order.phone %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @admin_order.comment %>
</p>

<p>
  <strong>Items:</strong>
  <% for item in @admin_order.items %>
    <%= item.title %>
  <% end %>
</p>

<%= link_to 'Edit', edit_admin_order_path(@admin_order) %> |
<%= link_to 'Back', admin_orders_path %>