config/routes.rb
Rails.application.routes.draw do
  get 'catalog' => 'catalog#index'

  get 'catalog/:category' => 'catalog#category'

  get 'catalog/:category/:item' => 'catalog#item'

  get 'cart'  => 'cart#index'

  get 'cart/checkout' => 'cart#checkout'

  post 'cart/order' => 'cart#order'

  get 'cart/success' => 'cart#success'

    get 'userlist/' => 'userlist#index'

    get 'userlist/show'

  namespace :admin do
    resources :orders
  end
  namespace :admin do
    resources :paytypes
  end
  namespace :admin do
    resources :pages
  end
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  namespace :admin do
    resources :reviews
  end
  namespace :admin do
    resources :postcomments
  end
  namespace :admin do
    resources :tags
  end
  namespace :admin do
    resources :posts
  end
  namespace :admin do
    resources :comments
  end
  namespace :admin do
    resources :actions
  end
  namespace :admin do
    resources :items
  end
  namespace :admin do
    resources :categories
  end

  root 'index#index'

  post '/addtocart' => 'cart#add' 

end

app/controllers/admin/actions_controller.rb
class Admin::ActionsController < ApplicationController
  layout "admin"
  before_filter :custom_user_auth
  before_action :set_admin_action, only: [:show, :edit, :update, :destroy]

  # GET /admin/actions
  # GET /admin/actions.json
  def index
    @admin_actions = Admin::Action.all
  end

  # GET /admin/actions/1
  # GET /admin/actions/1.json
  def show
  end

  # GET /admin/actions/new
  def new
    @admin_action = Admin::Action.new
  end

  # GET /admin/actions/1/edit
  def edit
  end

  # POST /admin/actions
  # POST /admin/actions.json
  def create
    @admin_action = Admin::Action.new(admin_action_params)

    respond_to do |format|
      if @admin_action.save
        format.html { redirect_to @admin_action, notice: 'Action was successfully created.' }
        format.json { render :show, status: :created, location: @admin_action }
      else
        format.html { render :new }
        format.json { render json: @admin_action.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/actions/1
  # PATCH/PUT /admin/actions/1.json
  def update
    respond_to do |format|
      if @admin_action.update(admin_action_params)
        format.html { redirect_to @admin_action, notice: 'Action was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_action }
      else
        format.html { render :edit }
        format.json { render json: @admin_action.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/actions/1
  # DELETE /admin/actions/1.json
  def destroy
    @admin_action.destroy
    respond_to do |format|
      format.html { redirect_to admin_actions_url, notice: 'Action was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_action
      @admin_action = Admin::Action.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_action_params
      params.require(:admin_action).permit(:title, :text, :image)
    end
end

app/helpers/admin/actions_helper.rb
module Admin::ActionsHelper
end

app/views/admin/actions/_form.html.erb
<%= form_for(@admin_action) do |f| %>
  <% if @admin_action.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_action.errors.count, "error") %> prohibited this admin_action from being saved:</h2>

      <ul>
      <% @admin_action.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text, class: "form-control ckeditor" %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit "Сохранить", :class => "btn btn-default" %>
  </div>
<% end %>

app/views/admin/actions/edit.html.erb
<h1>Editing Admin Action</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_action %> |
<%= link_to 'Back', admin_actions_path %>

app/views/admin/actions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Список акций</h1>

<table class="table table-responsive">
  <thead>
    <tr>
      <th>Название</th>
      <th>Описание</th>
      <th>Картинка</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_actions.each do |admin_action| %>
      <tr>
        <td><%= admin_action.title %></td>
        <td><%= admin_action.text %></td>
        <td><%= image_tag(admin_action.image, size: "100x100") %></td>
        <td><%= link_to 'Show', admin_action %></td>
        <td><%= link_to 'Edit', edit_admin_action_path(admin_action) %></td>
        <td><%= link_to 'Destroy', admin_action, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Action', new_admin_action_path %>

app/views/admin/actions/new.html.erb
<h1>New Admin Action</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_actions_path %>

app/views/admin/actions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @admin_action.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @admin_action.text %>
</p>

<p>
  <strong>Image:</strong>
  <%= @admin_action.image %>
</p>

<%= link_to 'Edit', edit_admin_action_path(@admin_action) %> |
<%= link_to 'Back', admin_actions_path %>